In [1]:
import numpy as np
import pandas as pd

In [2]:
credit_card_data = pd.read_csv('creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [8]:
l=credit_card_data[credit_card_data.Class == 0]
print(l.shape)

(284315, 31)

In [9]:
f=credit_card_data[credit_card_data.Class == 1]
print(f.shape)

(492, 31)

In [10]:
l.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
f.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
ls = l.sample(n=492)

In [13]:
nd = pd.concat([ls, f], axis=0)

In [14]:
nd

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
211011,138219.0,-0.352265,0.461915,-1.111244,-0.389064,1.480478,-1.147660,0.779506,-0.358451,0.271617,...,-0.156722,-0.194928,0.576792,0.497426,-2.138970,-0.199228,0.021685,0.386812,5.49,0
108842,71101.0,1.329357,0.019163,-1.779238,-0.623146,2.410952,2.947078,-0.081535,0.619985,-0.351083,...,-0.072997,-0.362172,-0.156436,1.055426,0.819991,0.548709,-0.073097,-0.005372,19.99,0
207856,136858.0,1.902335,0.203585,-2.464623,1.131814,1.198960,-0.793953,1.127035,-0.468797,-0.733163,...,0.418007,1.211755,-0.274995,0.787861,0.857482,-0.257656,-0.067603,-0.065748,84.00,0
115961,74089.0,1.074926,0.007112,0.378464,0.407001,0.289970,1.038779,-0.310751,0.424738,0.104172,...,-0.144237,-0.290804,0.271456,-0.968829,-0.113840,0.224337,0.039100,0.003166,1.00,0
172123,120972.0,1.796030,-1.162625,-1.212959,0.749653,-0.654939,-0.119875,-0.383074,0.018294,-0.259100,...,-0.157788,-0.126837,-0.053335,-0.472417,0.092573,-0.462415,0.006769,-0.038858,150.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [15]:
nd['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [16]:
nd.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94010.380081,-0.003385,0.052416,0.074337,-0.116608,-0.011926,-0.061216,0.039474,-0.022707,-0.008939,...,-0.047560,-0.015843,0.036444,-0.001231,0.034398,-0.006978,0.017659,0.043088,-0.000934,73.554228
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

### Splitting the data into Features & Targets

In [17]:
X = nd.drop(columns='Class', axis=1)
Y = nd['Class']

In [18]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
211011,138219.0,-0.352265,0.461915,-1.111244,-0.389064,1.480478,-1.147660,0.779506,-0.358451,0.271617,...,-0.469985,-0.156722,-0.194928,0.576792,0.497426,-2.138970,-0.199228,0.021685,0.386812,5.49
108842,71101.0,1.329357,0.019163,-1.779238,-0.623146,2.410952,2.947078,-0.081535,0.619985,-0.351083,...,0.042729,-0.072997,-0.362172,-0.156436,1.055426,0.819991,0.548709,-0.073097,-0.005372,19.99
207856,136858.0,1.902335,0.203585,-2.464623,1.131814,1.198960,-0.793953,1.127035,-0.468797,-0.733163,...,-0.039669,0.418007,1.211755,-0.274995,0.787861,0.857482,-0.257656,-0.067603,-0.065748,84.00
115961,74089.0,1.074926,0.007112,0.378464,0.407001,0.289970,1.038779,-0.310751,0.424738,0.104172,...,-0.263605,-0.144237,-0.290804,0.271456,-0.968829,-0.113840,0.224337,0.039100,0.003166,1.00
172123,120972.0,1.796030,-1.162625,-1.212959,0.749653,-0.654939,-0.119875,-0.383074,0.018294,-0.259100,...,-0.518344,-0.157788,-0.126837,-0.053335,-0.472417,0.092573,-0.462415,0.006769,-0.038858,150.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [19]:
Y

211011    0
108842    0
207856    0
115961    0
172123    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

### REGRESSIONS

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

### Split the data into Training data & Testing Data

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

### Model Training

In [25]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)

LogisticRegression()

### Accuracy Score

In [26]:
from sklearn.metrics import accuracy_score
training_data_accuracy=lr.score(X_train,Y_train)
print("ACCURACY=",training_data_accuracy)

ACCURACY= 0.928843710292249

### TEST ACCURACY

In [29]:
lr1=LogisticRegression()
lr1.fit(X_test,Y_test)

C:\Users\tarun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
lr1=LogisticRegression()
lr1.fit(X_test,Y_test)
print("ACCURACY=",lr1.score(X_test,Y_test))

ACCURACY= 0.934010152284264

C:\Users\tarun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(